### ISSUE TITLE
Ungleiche Darstellung der Zahlenwerte

### ISSUE THREAD

**Issue by s3tomack** [s3tomack/ProjectSimulator#5]
Nach Spielstart werden die meisten Zahlen ohne Nachkommastellen dargestellt, aber schon nach der ersten Runde ändert sich die Darstellung der geänderten Werte. Diese haben dann Nachkommastellen, aber teilweise in unterschiedlicher Anzahl. Dies sollte auf eine Darstellung von maximal 2 Nachkommastelle zu jeder Zeit des Spiels vereinheitlicht werden.

**Comment by on-delete** [comment]
Labels haben keine Möglichkeit, den angezeigten Text zu formatieren. Deshalb ist das so nicht lösbar. Eine Möglichkeit wäre, die Labels durch TextFields zu ersetzen, die haben sowas. Aber glaub da es mehr eine kosmetische Angelegenheit wäre und nicht die Funktionsweise beeinträchtigt, würde ich es hier dabei belassen.
